export const ALL_DESIGNER_REQUEST = "ALL_DESIGNER_REQUEST";
export const ALL_DESIGNER_SUCCESS = "ALL_DESIGNER_SUCCESS";
export const ALL_DESIGNER_FAIL = "ALL_DESIGNER_FAIL";


export const DESIGNER_DETAILS_REQUEST = "DESIGNER_DETAILS_REQUEST";
export const DESIGNER_DETAILS_SUCCESS = "DESIGNER_DETAILS_SUCCESS";
export const DESIGNER_DETAILS_FAIL = "DESIGNER_DETAILS_FAIL ";


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";



export const CLEAR_ERRORS = "CLEAR_ERRORS";